blueprint:
  name: Thermostat Finer Switching Temp Diff
  description: >
    Controls a thermostat with finer temperature control by temporarily adjusting 
    the target temperature when the actual temperature exceeds or falls below the 
    desired temperature. Uses scene snapshots to restore original settings after adjustment.
  domain: automation
  source_url: https://github.com/FabianGabor/HA-thermostat-finer-switching-temperature-differential

  input:
    thermostat:
      name: Thermostat
      description: The climate entity to control
      selector:
        entity:
          domain: climate

trigger:
  - trigger: state
    entity_id:
      - !input thermostat
    attribute: temperature
    id: kivant-homerseklet
    for:
      hours: 0
      minutes: 0
      seconds: 15

  - trigger: state
    entity_id:
      - !input thermostat
    attribute: current_temperature
    enabled: true
    for:
      hours: 0
      minutes: 0
      seconds: 15
    id: aktualis-homerseklet

condition: []

action:
  - action: scene.create
    metadata: {}
    data:
      snapshot_entities:
        - !input thermostat
      scene_id: thermostat_snapshot

  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ state_attr(input_thermostat, 'current_temperature') >
              state_attr(input_thermostat, 'temperature') }}
          - condition: state
            entity_id: !input thermostat
            attribute: hvac_action
            state: heating
        sequence:
          - action: climate.set_temperature
            target:
              entity_id: !input thermostat
            data:
              temperature: >-
                {{ (state_attr(input_thermostat, 'temperature') | float) - 0.5 }}
          - wait_for_trigger:
              - trigger: state
                entity_id:
                  - !input thermostat
                attribute: hvac_action
                to: idle
            timeout:
              hours: 0
              minutes: 1
              seconds: 0
              milliseconds: 0
            continue_on_timeout: false
          - action: scene.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: scene.thermostat_snapshot
        alias: "Aktuális > kívánt hőmérséklet "

      - conditions:
          - condition: template
            value_template: >-
              {{ state_attr(input_thermostat, 'current_temperature') <
              state_attr(input_thermostat, 'temperature') }}
          - condition: state
            entity_id: !input thermostat
            attribute: hvac_action
            state: idle
        sequence:
          - action: climate.set_temperature
            target:
              entity_id: !input thermostat
            data:
              temperature: >-
                {{ (state_attr(input_thermostat, 'temperature') | float) + 0.5 }}
          - wait_for_trigger:
              - trigger: state
                entity_id:
                  - !input thermostat
                attribute: hvac_action
                to: heating
            timeout:
              hours: 0
              minutes: 1
              seconds: 0
              milliseconds: 0
            continue_on_timeout: false
          - action: scene.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: scene.thermostat_snapshot
        alias: "Aktuális < kívánt hőmérséklet "

variables:
  input_thermostat: !input thermostat

mode: single
