blueprint:
  name: Thermostat Finer Switching Temp Diff
  description: Controls a Thermostat to have a finer temperature control.
  domain: automation
  source_url: https://github.com/home-assistant/home-assistant/pulls

  input:
    thermostat:
      name: Thermostat
      description: The thermostat to control
      selector:
        entity:
          domain: climate

    delay:
      name: Delay
      description: Delay between temperature adjustments
      default: 00:00:05
      selector:
        time:

    switching_differential:
      name: Switching Differential
      description: This is the temperature reduction value (in degrees) applied temporarily to the set target temperature when that target is reached. This decreased temperature lasts for the specified time before the original target temperature is restored, prompting the thermostat to idle mode.
      default: 0.5
      selector:
        number:
          min: 0.5
          max: 5.0
          step: 0.1
          mode: slider

trigger:
  - platform: template
    value_template: >-
      {% set current_temp = state_attr('input_thermostat', 'current_temperature') %}
      {% set set_temp = state_attr('input_thermostat', 'temperature') %}
      {{ current_temp is not none and set_temp is not none and current_temp >= set_temp }}
  - platform: homeassistant
    event: start

action:
  - wait_template: "{{ states('input_thermostat') not in ['unknown', 'unavailable', None] }}"
    timeout: "00:05:00"    # Timeout to prevent indefinite waiting, adjust as needed.
    continue_on_timeout: false

  - condition: template
    value_template: "{{ state_attr('input_thermostat', 'current_temperature') >= state_attr('input_thermostat', 'temperature') }}"

  - service: climate.set_temperature
    data_template:
      entity_id: !input thermostat
      temperature: "{{ state_attr(trigger.entity_id, 'temperature')|float - states('input_number.switching_differential')|float }}"
  - delay: !input delay
  - service: climate.set_temperature
    data_template:
      entity_id: !input thermostat
      temperature: "{{ state_attr(trigger.entity_id, 'temperature')|float }}"