blueprint:
  name: Thermostat Finer Switching Temp Diff
  description: Controls a Thermostat to have a finer temperature control.
  domain: automation
  source_url: https://github.com/home-assistant/home-assistant/pulls

  input:
    thermostat:
      name: Thermostat
      description: The thermostat to control
      selector:
        entity:
          domain: climate
    delay:
      name: Delay
      description: Delay between temperature adjustments
      default: 00:00:05
      selector:
        time:
    switching_differential:
      name: Switching Differential
      description: This is the temperature reduction value (in degrees) applied temporarily to the set target temperature when that target is reached. This decreased temperature lasts for the specified time before the original target temperature is restored, prompting the thermostat into idle mode.
      default: 0.5
      selector:
        number:
          min: 0.5
          max: 1.0
          step: 0.1
          mode: slider
    repeat_interval:
      name: Repeat Interval
      description: How often the thermostat check should be repeated
      default: 00:05:00
      selector:
        time:

trigger:
  - platform: state
    entity_id: !input thermostat
  - platform: time_pattern
    minutes: "/{{ (input_repeat_interval.split(':')[1])|int }}"

condition:
  - condition: template
    value_template: "{{ state_attr(trigger.entity_id, 'current_temperature')|float > state_attr(trigger.entity_id, 'temperature')|float }}"

action:
  - service: climate.set_temperature
    data:
      entity_id: !input thermostat
      temperature: "{{ state_attr(trigger.entity_id, 'temperature')|float - states('input_text.switching_differential')|float }}"
  - delay: !input delay
  - service: climate.set_temperature
    data:
      entity_id: !input thermostat
      temperature: "{{ state_attr(trigger.entity_id, 'temperature')|float }}"