blueprint:
  name: Thermostat Finer Switching Temp Diff [dev]
  description: Controls multiple Thermostats to have a finer temperature control.
  domain: automation
  source_url: https://github.com/FabianGabor/HA-thermostat-finer-switching-temperature-differential/blob/dev/thermostat-finer-switching-temp-diff.yaml

  input:
    thermostats:
      name: Thermostats
      description: The thermostats to control
      selector:
        entity:
          domain: climate
          multiple: true

    delay:
      name: Delay
      description: Delay between temperature adjustments
      default: 00:00:05
      selector:
        time:

    switching_differential:
      name: Switching Differential
      description: This is the temperature reduction value (in degrees) applied temporarily to the set target temperature when that target is reached. This decreased temperature lasts for the specified time before the original target temperature is restored, prompting the thermostat to idle mode.
      default: 0.5
      selector:
        number:
          min: 0.5
          max: 5.0
          step: 0.1
          mode: slider

trigger:
  - platform: state
    entity_id: !input 'thermostats'

action:
  - choose:
    - conditions: "{{ states(trigger.entity_id) not in ['unknown', 'unavailable', None] }}"
      sequence:
        - condition: template
          value_template: "{{ state_attr(trigger.entity_id, 'current_temperature') >= state_attr(trigger.entity_id, 'temperature') }}"
        - service: climate.set_temperature
          data_template:
            entity_id: "{{ trigger.entity_id }}"
            temperature: "{{ state_attr(trigger.entity_id, 'temperature')|float - states('input_number.switching_differential')|float }}"
        - delay: !input delay
        - service: climate.set_temperature
          data_template:
            entity_id: "{{ trigger.entity_id }}"
            temperature: "{{ state_attr(trigger.entity_id, 'temperature')|float }}"