blueprint:
  name: Thermostat Finer Switching Temp Diff
  description: Controls a Thermostat to have a finer temperature control.
  domain: automation
  source_url: https://github.com/home-assistant/home-assistant/pulls

  input:
    thermostat:
      name: thermostat
      description: The thermostat to control
      selector:
        entity:
          domain: climate
    delay:
      name: Delay
      description: Delay between temperature adjustments
      default: 00:00:05
      selector:
        time:
    switching_differential:
      name: Switching Differential
      description: Temperature range for switching (in degrees)
      default: 0.5
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1
          mode: slider

trigger:
  - platform: state
    entity_id: !input thermostat

condition:
  - condition: template
    value_template: "{{ state_attr(trigger.entity_id, 'current_temperature')|float > state_attr(trigger.entity_id, 'temperature')|float }}"

action:
  - service: climate.set_temperature
    data:
      entity_id: !input thermostat
      temperature: "{{ state_attr(trigger.entity_id, 'temperature')|float - states('input_text.switching_differential')|float }}"
  - delay: !input delay
  - service: climate.set_temperature
    data:
      entity_id: !input thermostat
      temperature: "{{ state_attr(trigger.entity_id, 'temperature')|float }}"
