blueprint:
  name: Thermostat Finer Switching Temp Diff
  description: Controls a Thermostat to have a finer temperature control.
  domain: automation
  source_url: https://github.com/home-assistant/home-assistant/pulls

  input:
    thermostat:
      name: Thermostat
      description: The thermostat to control
      selector:
        entity:
          domain: climate

    delay:
      name: Delay
      description: Delay between temperature adjustments
      default: 00:00:10
      selector:
        time:

    switching_differential:
      name: Switching Differential
      description: This is the temperature reduction value (in degrees) applied temporarily to the set target temperature when that target is reached. This decreased temperature lasts for the specified time before the original target temperature is restored, prompting the thermostat to idle mode.
      default: 0.5
      selector:
        number:
          min: 0.5
          max: 3.0
          step: 0.5
          mode: slider

trigger:
  - platform: state
    entity_id: !input 'thermostats'
    attribute: current_temperature

action:
  - condition: template
    value_template: "{{ state_attr(trigger.entity_id, 'current_temperature') >= state_attr(trigger.entity_id, 'temperature') }}"
  - condition: template
    value_template: "{{ is_state_attr(trigger.entity_id, 'hvac_action', 'heating') }}"
  - delay: !input delay
  - service: climate.set_temperature
    target:
      entity_id: "{{ trigger.entity_id }}"
    data:
      temperature: "{{ state_attr(trigger.entity_id, 'temperature')|float - states('input_number.switching_differential')|float(default=0.5) }}"
  - delay: !input delay
  - service: climate.set_temperature
    target:
      entity_id: "{{ trigger.entity_id }}"
    data:
      temperature: "{{ state_attr(trigger.entity_id, 'temperature')|float + states('input_number.switching_differential')|float(default=0.5) }}"
